services:
  - type: web
    name: cnc-ai-app
    runtime: python
    region: frankfurt
    plan: free
    rootDir: .

    buildCommand: >-
      apt-get install -y poppler-utils tesseract-ocr &&
      pip install -r requirements.txt &&
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&
      apt-get install -y nodejs &&
      npm install &&
      npm run build

    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DEBUG_ERRORS
        value: "1"
